#!/usr/bin/env python3
"""Generate src/moonblaster_tables.py from the MoonBlaster Wave player's
table sources (demo-disks/moonsound_11/*.inc).

The player resolves a wave preset + note to an OPL4 tone and pitch through
these tables (mwm_player.asm: MBPlayer_calc_wave, calc_drm and the RAM-kit
path). Rather than parsing Z80 sources at conversion time, this script
assembles the db/dw tables once and emits plain Python data:

  PATCHES[p]   p = 0..174: dict(flag, lfo_vib, regs, splits)
               splits: list of (upper_bound, tone, tnote, fnums[12])
  DRUM_MIDI    patch record used by the GM drum kit for notes a < 36
  GM_DRUMS[a-36] a = 36..86: (tone, freq_word, lfo_vib, regs)
  FRQTAB_AMIGA / FRQTAB_44K / FRQTAB_TURBO: RAM-kit freq words by note n

Usage: python3 scripts/gen_moonblaster_tables.py [path/to/moonsound_11]
"""

import os
import re
import sys
import pprint

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SRC = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'demo-disks', 'moonsound_11'))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'moonblaster_tables.py'))

INC_FILES = ['freq_table_0.inc', 'freq_table_1.inc', 'freq_table_2.inc',
             'freq_table_3.inc', 'patch_table.inc', 'freq_table_4.inc']


def assemble(src_dir):
    """Assemble db/dw/label lines into a flat memory image + label map."""
    def conv(expr):
        return re.sub(r'\b([0-9][0-9a-fA-F]*)[hH]\b', lambda m: str(int(m.group(1), 16)), expr)

    items, labels, pc = [], {}, 0
    for fn in INC_FILES:
        for line in open(os.path.join(src_dir, fn), encoding='latin-1'):
            line = line.split(';')[0].rstrip()
            if not line.strip():
                continue
            m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*):?\s*(.*)$', line)
            if m and not line[0].isspace():
                labels[m.group(1)] = pc
                line = m.group(2)
            line = line.strip()
            if not line:
                continue
            m = re.match(r'^(db|dw)\s+(.*)$', line, re.I)
            if not m:
                raise SystemExit(f'{fn}: unparsed line: {line}')
            kind = m.group(1).lower()
            for arg in (a.strip() for a in m.group(2).split(',') if a.strip()):
                items.append((pc, kind, conv(arg)))
                pc += 1 if kind == 'db' else 2
    mem = bytearray(pc)
    for addr, kind, expr in items:
        v = eval(expr, {}, labels)
        mem[addr] = v & 0xFF
        if kind == 'dw':
            mem[addr + 1] = (v >> 8) & 0xFF
    return mem, labels


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    mem, lab = assemble(src)

    def w(a):
        return mem[a] | (mem[a + 1] << 8)

    def fnums(addr):
        return [w(addr + 2 * i) for i in range(12)]

    def header_regs(hp):
        lfo_vib, regs, a = mem[hp], [], hp + 1
        while mem[a] != 0xFF:
            regs.append((mem[a], mem[a + 1]))
            a += 2
        return lfo_vib, regs

    def patch_record(rec, max_splits=None):
        flag = mem[rec]
        lfo_vib, regs = header_regs(w(rec + 1))
        splits, a = [], rec + 3
        while True:
            bound, tone_lo, tn = mem[a], mem[a + 1], mem[a + 2]
            splits.append((bound, tone_lo | ((tn & 1) << 8), tn >> 1, fnums(w(a + 3))))
            if bound == 255 or (max_splits and len(splits) >= max_splits):
                break
            a += 5
        return dict(flag=flag, lfo_vib=lfo_vib, regs=regs, splits=splits)

    pt = lab['MBPlayer_patch_table']
    patches = [patch_record(w(pt + 2 * p)) for p in range(175)]
    # patch_table[175] = drum_midi: the GM drum kit's fallback for notes
    # a < 36 (calc_drm jumps back into the patch path). A single split
    # bounded at 36, not 255-terminated.
    drum_midi = patch_record(w(pt + 2 * 175), max_splits=1)

    gm = lab['gmdrm_c4']
    gm_drums = []
    for i in range(0x56 - 36 + 1):
        e = gm + 5 * i
        lfo_vib, regs = header_regs(w(e + 3))
        gm_drums.append((mem[e], w(e + 1), lfo_vib, regs))

    def frqtab(label):
        a = lab[label]
        return [w(a + 2 * n) for n in range(96)]   # 96 words (8 octaves)

    out = [
        '"""MoonBlaster Wave player tables (GENERATED - do not edit).',
        '',
        'Generated by scripts/gen_moonblaster_tables.py from the reference',
        'player sources (demo-disks/moonsound_11: patch_table.inc,',
        'freq_table_*.inc). See that script for the record formats.',
        '"""',
        '',
        f'PATCHES = {pprint.pformat(patches, width=120, compact=True)}',
        '',
        f'DRUM_MIDI = {pprint.pformat(drum_midi, width=120, compact=True)}',
        '',
        f'GM_DRUMS = {pprint.pformat(gm_drums, width=120, compact=True)}',
        '',
        f'FRQTAB_AMIGA = {frqtab("MBPlayer_frqtab_amiga")!r}',
        f'FRQTAB_44K = {frqtab("MBPlayer_frqtab_441khz")!r}',
        f'FRQTAB_TURBO = {frqtab("MBPlayer_frqtab_turbo")!r}',
        '',
    ]
    with open(OUT, 'w') as f:
        f.write('\n'.join(out))
    print(f'wrote {OUT}: {len(patches)} patches, {len(gm_drums)} GM drum notes')


if __name__ == '__main__':
    main()
